baseURL = 'https://me.nerocrux.com/'
languageCode = 'en-us'
title = 'nerocrux'
theme = "hugo-theme-m10c"
avatar = "assets/N512.png"
assetDir = "assets"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Peichao Yu"
  description = "Software engineer."
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/nerocrux"
  [[params.social]]
    icon = "brand-x"
    name = "X"
    url = "https://twitter.com/nerocrux"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/peichao-yu-458b5218/"
