baseURL = 'https://me.nerocrux.com/'
languageCode = 'en-us'
title = 'nerocrux'
theme = "hugo-theme-m10c"
avatar = "avatar.jpg"

[pagination]
  pagerSize = 8

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params]
  author = "Peichao Yu"
  description = "Software engineer."
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/nerocrux"
  [[params.social]]
    icon = "brand-x"
    name = "X"
    url = "https://twitter.com/nerocrux"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/peichao-yu-458b5218/"
